/// Flutter icons CustomIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData th_large_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData complete = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData management = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reservations = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb_empty = IconData(0xf00b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
